### ISSUE TITLE
No se puede crear primer usuario administrador

### ISSUE THREAD

**Issue by rojinegr0** [adri1336/keflix_server#5]
Creé el archivo .env y activé el modo depuración (DEBUG_ENABLED = true), se inicia sin aparente error.

> --- KEFLIX SERVER 1.1.0 ---
> Desarrollado por: adri1 (https://github.com/adri1336/)
> 
> OK! Servidor encendido y escuchando por el puerto: 3000
> OK! Base de datos conectada
> OK! Base de datos sincronizada:
>         Cuentas: 0
>         Perfiles: 0
>         Géneros: 0
>         Películas: 0
>         Series: 0

Tengo esta configuración en el archivo .env:

> APP_PORT = 3000
> ACCESS_TOKEN_SECRET = D6DcxG73t52cbg5T
> ACCESS_TOKEN_EXPIRES_IN = 3d
> REFRESH_TOKEN_SECRET = YnrAd7nz5n5MY3wK
> REFRESH_TOKEN_EXPIRES_IN = 7d
> MEDIA_PATH = C:\Users\Home\Videos\Peliculas
> DATABASE_PATH = C:\Users\Home\Downloads\Compressed\keflix_server\x64\database.sqlite
> DEBUG_ENABLED = true
> DATABASE_LOGGING = false
> FORCE_DATABASE_SYNC = false

Agradezco me puedan ayudar por favor.

Edit. Olvidé mencionar, todo esto en Windows 10.

**Comment by adri1336** [comment]
Use `DEBUG_ENABLED = 1` en vez de true

**Comment by rojinegr0** [comment]
Muchas gracias, ya funciona todo bien.

**Comment by adri1336** [comment]
Genial
