### ISSUE TITLE
Arranco el servidor pero no añade ningun fichero .mkv de los que hay en el path

### ISSUE THREAD

**Issue by zjuanma** [adri1336/keflix_server#6]
He añadido un path en el fichero .env con mi biblioteca de videos .mkv, pero el servidor dice que tiene 0 peliculas y 0 series.

¿Que puedo mirar para ver que esta ocurriendo?

**Comment by adri1336** [comment]
Las películas o series se tienen que añadir desde la aplicación admin: https://github.com/adri1336/keflix_admin
Una vez añadidas puedes transportar la base de datos (database.sqlite) y las películas a cualquier sitio e indicarle la ruta.
